### ISSUE TITLE
CI run failures on 8.x

### ISSUE THREAD

**Issue by mhdawson** [pkgjs/support#9]
Seems like one of the packages I pulled in(or one of the dependencies does not support 8.x) Not sure why I did not see that on the PR itself but I must have missed that.

@wesleytodd, @ljharb I seem to remember we'd agreed that the support tool would only need to run on latest LTS releases? If so maybe I just need to update the CI config.

**Comment by ljharb** [comment]
At a minimum, yes. Depending on the dependency tho, we may be able to swap it out for something more robust.

**Comment by rodion-arr** [comment]
@mhdawson @wesleytodd 
I've mage a small investigation here and it looks like it is failing because of `got` lib (https://github.com/sindresorhus/got).

It is requiring node 10+
https://github.com/sindresorhus/got/blob/master/package.json#L10

I can help to migrate to other http lib like axios (or other) or update CI in order to drop node 8.x, WDYT?

**Comment by ljharb** [comment]
We could drop `got` to v9, or switch to another lib.

**Comment by mhdawson** [comment]
I'd prefer not to use an older version as that might be a problem if there are security issues etc.  I'm kind of thinking that even for maintainers that want to support older Node.js versions they should still also be testing/using LTS versions and so supporting only current LTS versions would be ok for this kind of tool.

**Comment by mhdawson** [comment]
@rodion-arr also wanted to say thanks for taking a look :)
